config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|vi/ do
    namespace :auth do
      resource :registration do
        collection do
          get 'forgot_password', to: 'registrations#forgot_password'
        end
      end
      resources :sessions, only: %i[new create]
      delete '/logout', to: 'sessions#destroy'
    end
    namespace :record do
      resources :staff_management, only: [:index]
      resource :profile
      get 'profile/setting', to: 'profiles#profile_setting'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/petition.rb
class Petition < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :image
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  belongs_to :post_type
end

app/models/post_type.rb
class PostType < ApplicationRecord

  validates :name, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"

  has_one_attached :avatar

  enum gender: { male: 0, fmale: 1, other: 2 }

  validates :phone_number , presence: true, format: { with: Settings.regex.number_phone }
  validates :first_name, presence: true, length: { in: 2...20 }
  validates :last_name, presence: true, length: { in: 2...20 }
  validates :address, presence: true, length: { in: 10...50 }
  validates :birthdate, presence: true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  enum role: { employee: 0, manager: 1, admin: 2 }

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { in: 6..20 }
  validates :password, presence: true, length: { in: 6...20}
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: Settings.regex.email }

end

app/models/working_time.rb
class WorkingTime < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"

  validates :working_date, presence: true
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :workdays, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  # include WardenHelper
  include ErrorHandler

  before_action :set_locale

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = if I18n.available_locales.include?(locale)
                    locale
                  else
                    I18n.default_locale
                  end
  end

  def default_url_options
    { locale: I18n.locale }
  end

  private
  def current_user
    request.env['warden'].user
  end

  def warden
    request.env['warden']
  end
end

app/controllers/concerns/error_handler.rb
module ErrorHandler
  extend ActiveSupport::Concern

  # included do
  #   rescue_from Exception do |e|
  #     redirect_to new_auth_session_path, flash: { error: I18n.t('.sign_in.fail')}
  #   end
  # end

end

app/controllers/concerns/warden_helper.rb
module WardenHelper
  extend ActiveSupport::Concern

  included do
    helper_method :warden, :logged_in?, :current_user

    prepend_before_action :authenticate!
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    request.env['warden'].user
  end

  def warden
    request.env['warden']
  end

  def authenticate!
    warden.authenticate!
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController
  layout 'admin'
  # before_action :authenticate!
end

app/controllers/record/profiles_controller.rb
class Record::ProfilesController < DashboardController
  before_action :find_profile, only: [:edit, :update, :show]
  def new;  end

  def create
    service.create_profile
    flash[:success] = I18n.t('.profile.create.success')
    redirect_to record_profile_path
  end

  def edit; end

  def update
    service.update_profile(@profile)
    flash[:success] = I18n.t('profile.update.success')
    redirect_to record_profile_path
  end

  def show; end

  def profile_setting
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile.nil?
      @profile = Profile.new
      render 'new'
    else
      render 'edit'
    end
  end
  private

  def find_profile
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def parameters
    parameters ||= Record::ProfileParams.new params
  end

  def service
    service ||= Record::ProfileService.new(parameters, current_user)
  end
end

app/controllers/unauthorized_controller.rb
class UnauthorizedController < BaseController
  def self.call(env)
    @respond ||= action(:respond)
    @respond.call(env)
  end

  def respond
    self.response_body = "Unauthorized Action"
    self.status = :unauthorized
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/record/profile_helper.rb
module Record::ProfileHelper
end

app/helpers/unauthorized_helper.rb
module UnauthorizedHelper
end

app/views/layouts/admin.html.slim
html
  head
    title QuanLiDoanhNghiep
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render "layouts/admin_layout/navbar"
    = render "layouts/admin_layout/sidebar"
    .main-content.d-flex.flex-column.hide-sidemenu
      = toastr_flash
      = yield
      = render partial: "layouts/admin_layout/footer"
    / = toastr_flash
    / = yield
    / = render "layouts/admin_layout/footer"

app/views/layouts/admin_layout/_footer.html.slim
.flex-grow-1
footer.footer.mt-1
  p Copyright © 2020
    | Plab. All rights reserved

app/views/layouts/admin_layout/_navbar.html.slim
nav.navbar.navbar-expand.fixed-top.top-menu
  a.navbar-brand href="<%= dashboard_sales_path %>"
    = image_tag("large-logo.png", alt: "Large Logo", class: "large-logo")

    = image_tag("small-logo.png", alt: "Small Logo", class: "small-logo")
  .burger-menu.toggle-menu
    span.top-bar
    span.middle-bar
    span.bottom-bar

  .collapse.navbar-collapse#navbarSupportedContent
    ul.left-nav.d-none.d-md-block.navbar-nav
      li.nav-item.dropdown.mega-menu
        a.nav-linkd.ropdown-toggle href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          .mega-menu-btn
            Mega Menu
            i.icon data-feather="chevron-down"
        .dropdown-menu
          .container
            .row
              .col-lg-3.col-md-6
                h5.title Features
                a.dropdown-item
                  | Alerts
                a.dropdown-item
                  | Badges
                a.dropdown-item
                  | Buttons

              .col-lg-3.col-md-6
                h5.title Features
                a.dropdown-item
                  | Cards
                a.dropdown-item
                  | Dropdowns
                a.dropdown-item
                  | Forms

              .col-lg-3.col-md-6
                h5.title Features
                a.dropdown-item
                  | List Groups
                a.dropdown-item
                  | Modals
                a.dropdown-item
                  | Progress Bars

              .col-lg-3.col-md-6
                h5.title Features
                a.dropdown-item
                  | Tables
                a.dropdown-item
                  | Tabs
                a.dropdown-item
                  | Sign Up

    form.nav-search-form.d-none.d-sm-block
      input.form-control placeholder="Search..." type="text"
      button.search-success type="submit"
        i.icon data-feather="search"


    .ul.navbar-nav.right-nav.ml-auto
      li.nav-item.dropdown.message-box.d-none.d-sm-block
        a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          .count-info
            i.icon data-feather="mail"
            span.ci-number.theme-bg
              span.ripple.theme-bg
              span.ripple.theme-bg
              span.ripple.theme-bg


        .dropdown-menu
          a.dropdown-item href="javascript:void(0);"
          .message-item
            .user-pic
              = image_tag("user/1.jpg", alt: "User Image", class: "rounded-circle")
              span.profile-status.online
            .chat-content
              span.message-title Aaron Rossi
              span.mail-desc Just sent a new comment!
            span.time 0 seconds ago

          a.dropdown-item href="javascript:void(0);"
          .message-item
            .user-pic
              = image_tag("user/2.jpg", alt: "User Image", class: "rounded-circle")
              span.profile-status.ofline
            .chat-content
              span.message-title Marco Gomez
              span.mail-desc Just sent a new comment!
            span.time 5 minutes ago


            a.dropdown-item href="javascript:void(0);"
            .message-item
              .user-pic
                = image_tag("user/3.jpg", alt: "User Image", class: "rounded-circle")
                span.profile-status.away
              .chat-content
                span.message-title Mitch Petty
                span.mail-desc Just sent a new comment!
              span.time 9:00 AM
            a.dropdown-item href="javascript:void(0);"
              | See all emails
              i.icon data-feather="chevron-right"

        <!-- Message Notification dropdown -->
      li.message-box.dropdown.nav-item
        a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          .count-info
            i.icon data-feather="bell"
            span.ci-number
              span.ripple
              span.ripple
              span.ripple
        .dropdown-menu
          a.dropdown-item href="javascript:void(0);"
          .message-item
            .user-pic
              = image_tag("user/4.jpg", alt: "User Image", class: "rounded-circle")
              span.profile-status.online
            .chat-content
              span.message-title Aaron Rossi
              span.mail-desc Just sent a new comment!
            span.time 0 seconds ago
          a.dropdown-item href="javascript:void(0);"
          .message-item
            .user-pic
              = image_tag("user/5.jpg", alt: "User Image", class: "rounded-circle")
              span.profile-status.ofline
            .chat-content
              span.message-title Marco Gomez
              span.mail-desc Just sent a new comment!
            span.time 5 minutes ago
          a.dropdown-item href="javascript:void(0);"
          .message-item
            .user-pic
              = image_tag("user/6.jpg", alt: "User Image", class: "rounded-circle")
              span.profile-status.away
            .chat-content
              span.message-title Mitch Petty
              span.mail-desc
                | New order received!
                span.amount $250
            span.time 9:00 AM - 02-02-2019
          a.dropdown-item href="javascript:void(0);"
            | Check all notifications
            i.icon data-feather="chevron-right"


        <!-- Profile dropdown -->
      li.nav-item.dropdown.profile-nav-item
        a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          .menu-profile
            span.name Aaron Rossi
            = image_tag("profile.jpg", alt: "Profile Image", class: "rounded-circle")
        .dropdown-menu
          = link_to  record_profile_path, class: 'dropdown-item'
            i.icon data-feather="user"
            | Profile
          a.dropdown-item href="inbox.html"
            i.icon data-feather="inbox"
            | Mailbox
          a.dropdown-item href="chat.html"
            i.icon data-feather="help-circle"
            | Support
          = link_to  record_profile_setting_path, class: 'dropdown-item'
            i.icon data-feather="settings"
            | Settings
          = link_to  auth_logout_path , method: :delete, class: 'dropdown-item'
            i.icon data-feather="log-out"
            | Logout

app/views/layouts/admin_layout/_sidebar.html.slim
<!-- Side Menu -->
.sidemenu-area.sidemenu-toggle.default
  nav.sidemenu.navbar.navbar-expand.navbar-light.hide-nav-title
    .navbar-collapse.collapse
      .navbar-nav
        .nav-item.dropdown
            a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              .dropdown-title
                i.icon data-feather="grid"
                span.title
                  | Dashboard
                  i.icon.fr data-feather="chevron-right"
            .dropdown-menu
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Sales
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | eCommerce
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Analytics
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | CRM
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Project

        a.nav-link
          i.icon data-feather="inbox"
          span.title Inbox
        a.nav-link
          i.icon data-feather="message-square"
          span.title Chat
        a.nav-link
          i.icon data-feather="check-square"
          span.title Todo List
        a.nav-link
          i.icon data-feather="file-text"
          span.title Notes
        a.nav-link
          i.icon data-feather="search"
          span.title Search

        .nav-item.dropdown.super-color
          a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            .dropdown-title
              i.icon data-feather="filter" 
              span.title
                | UI Components
                i.icon.fr data-feather="chevron-right" 


          .dropdown-menu
            a.dropdown-item
              i.icon data-feather="bell"
              | Alerts
            a.dropdown-item
              i.icon data-feather="award"
              | Badges
            a.dropdown-item
              i.icon data-feather="arrow-right-circle"
              | Buttons
            a.dropdown-item
              i.icon data-feather="layers"
              | Cards
            a.dropdown-item
              i.icon data-feather="arrow-down-circle"
              | Dropdowns
            a.dropdown-item
              i.icon data-feather="file-text"
              | Forms
            a.dropdown-item
              i.icon data-feather="list"
              | List Groups
            a.dropdown-item
              i.icon data-feather="airplay"
              | Modals
            a.dropdown-item
              i.icon data-feather="trending-up"
              | Progress Bars
            a.dropdown-item
              i.icon data-feather="database"
              | Tables
            a.dropdown-item
              i.icon data-feather="triangle"
              | Tabs

        .nav-item.dropdown
          a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            .dropdown-title
              i.icon data-feather="user"
              span.title
                | User
                i.icon.fr data-feather="chevron-right"
            .dropdown-menu
              a.dropdown-item target="_blank"
                i.icon data-feather="user-plus"
                | Sign Up
              a.dropdown-item target="_blank"
                i.icon data-feather="user-check"
                | Login
              a.dropdown-item target="_blank"
                i.icon data-feather="unlock"
                | Forgot Password


        .nav-item.dropdown
          a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            .dropdown-title
              i.icon data-feather="bar-chart-2"
              span.title
                | Charts
                i.icon.fr data-feather="chevron-right"
            .dropdown-menu
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Line Charts
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Area Charts
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Column Charts
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Bar Charts
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Mixed Charts
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Pie and Donuts Charts
        .dropdown.nav-item
          a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            .dropdown-title
              i.icon data-feather="heart"
              span.title
                | Icons
                i.icon.fr data-feather="chevron-right"
            .dropdown-menu
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Feather Icons
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Line Icons
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Icofont Icons
        .nav-item.dropdown
          a.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            .dropdown-title
              i.icon data-feather="file-text"
              span.title
                | Pages
                i.icon.fr data-feather="chevron-right"
            .dropdown-menu
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Users Card
              a.dropdown-item
                i.icon data-feather="chevron-right"
                span.title Notifications
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Time line
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Invoice Template
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Gallery
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Faq
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Pricing
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Profile
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Profile Settings
              a.dropdown-item
                i.icon data-feather="chevron-right"
                | Error 404

app/views/layouts/application.html.slim
html
  head
    title QuanLiDoanhNghiep
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = toastr_flash
    = yield